services:
  nginx:
    image: ghcr.io/nekroorganization/nginx:prod
    ports:
      - "80:80"          # http ззовні
      # - "443:443"     # якщо додаси TLS
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
    volumes:
      - /opt/myapp/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  frontend:
    image: ghcr.io/nekroorganization/frontend:prod
    ports:
      - "3000:3000"      # хочеш мати прямий доступ
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    image: ghcr.io/nekroorganization/backend:prod
    ports:
      - "8000:8000"      # прямий доступ
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/health >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
