# Generated by Django 5.2.4 on 2025-07-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='openquestion',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='truefalsequestion',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='CourseTheory',
        ),
        migrations.DeleteModel(
            name='OpenQuestion',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='TrueFalseQuestion',
        ),
        migrations.DeleteModel(
            name='TestAnswer',
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
    ]
