# Generated by Django 5.2.4 on 2025-08-17 19:09

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_purchasedcourse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 17, 19, 5, 42, 952029, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=240, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='coursedone',
            unique_together={('course', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='purchasedcourse',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['course', 'created_at'], name='course_comm_course__d9ef1b_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='course_cour_slug_235a66_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='course_cour_status_57ffd9_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='course_cour_categor_ce9f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='coursedone',
            index=models.Index(fields=['user', 'course'], name='course_cour_user_id_37b1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedcourse',
            index=models.Index(fields=['user', 'course'], name='course_purc_user_id_67b87c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedcourse',
            index=models.Index(fields=['course', 'is_active'], name='course_purc_course__d57a7c_idx'),
        ),
    ]
