# Generated by Django 5.2.4 on 2025-08-23 09:03

import admin_panel.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('selfie_photo', models.ImageField(blank=True, null=True, upload_to=admin_panel.models.upload_teacher_doc)),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to=admin_panel.models.upload_teacher_doc)),
                ('diploma_photo', models.ImageField(blank=True, null=True, upload_to=admin_panel.models.upload_teacher_doc)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
