# Generated by Django 5.2.4 on 2025-09-21 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('course', '0001_initial'),
        ('lesson', '0003_alter_lesson_unique_together_alter_lesson_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'id'], name='msg_chat_id_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='msg_chat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='readmarker',
            index=models.Index(fields=['chat', 'user'], name='rm_chat_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.CheckConstraint(condition=models.Q(('student', models.F('teacher')), _negated=True), name='chk_chat_student_not_teacher'),
        ),
    ]
