# Generated by Django 5.2.4 on 2025-08-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='stories/covers/')),
                ('published_at', models.DateTimeField()),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
