# Generated by Django 5.2.4 on 2025-08-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tags',
        ),
    ]
