# Generated by Django 5.2.4 on 2025-07-20 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openquestion',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='truefalsequestion',
            name='lesson',
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.IntegerField(default=0)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='lesson.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='openquestion',
            name='test',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='open_questions', to='lesson.test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='lesson.test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truefalsequestion',
            name='test',
            field=models.ForeignKey(default=22.57, on_delete=django.db.models.deletion.CASCADE, related_name='true_false_questions', to='lesson.test'),
            preserve_default=False,
        ),
    ]
