# Generated by Django 5.2.4 on 2025-09-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('code', 'Code'), ('file', 'File'), ('quote', 'Quote'), ('checklist', 'Checklist'), ('html', 'HTML'), ('columns', 'Columns'), ('callout', 'Callout')], max_length=16),
        ),
    ]
