# Generated by Django 5.2.4 on 2025-08-01 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_rename_is_true_truefalsequestion_correct_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionattempt',
            unique_together={('attempt', 'question_text')},
        ),
        migrations.CreateModel(
            name='TestAnswerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.testquestion')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.testanswer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
