# Generated by Django 5.2.4 on 2025-08-08 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_alter_questionattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_tests', to='lesson.lesson'),
        ),
    ]
