# Generated by Django 5.2.4 on 2025-08-17 19:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_category_options_alter_comment_options_and_more'),
        ('lesson', '0006_alter_test_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetheory',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='openquestion',
            name='test',
        ),
        migrations.AlterUniqueTogether(
            name='questionattempt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='test',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='test',
        ),
        migrations.RemoveField(
            model_name='truefalsequestion',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testanswerattempt',
            name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='testanswerattempt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testanswerattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'title')},
        ),
        migrations.AddField(
            model_name='lesson',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_covers/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 17, 19, 5, 54, 541366, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2025, 8, 17, 19, 6, 20, 492696, tzinfo=datetime.timezone.utc), max_length=220, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='lesson',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('code', 'Code'), ('file', 'File'), ('quote', 'Quote'), ('checklist', 'Checklist'), ('html', 'HTML')], max_length=16)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='lesson.lesson')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('not_started', 'Not started'), ('started', 'Started'), ('completed', 'Completed')], default='not_started', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lesson.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='course.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='lesson.module'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course'], name='lesson_less_course__e68048_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module'], name='lesson_less_module__44ae21_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status'], name='lesson_less_status_faff9e_idx'),
        ),
        migrations.DeleteModel(
            name='CourseTheory',
        ),
        migrations.DeleteModel(
            name='OpenQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TrueFalseQuestion',
        ),
        migrations.DeleteModel(
            name='TestAnswer',
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
        migrations.DeleteModel(
            name='TestAnswerAttempt',
        ),
        migrations.DeleteModel(
            name='TestAttempt',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['lesson', 'order'], name='lesson_less_lesson__6b2f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'lesson'], name='lesson_less_user_id_21f8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'state'], name='lesson_less_lesson__43752e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'title')},
        ),
    ]
