# Generated by Django 5.2.4 on 2025-08-21 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('single', 'Single choice'), ('multiple', 'Multiple choice'), ('true_false', 'True/False'), ('short', 'Short answer'), ('long', 'Long answer'), ('code', 'Code'), ('match', 'Matching'), ('order', 'Ordering')], max_length=16)),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('difficulty', models.PositiveSmallIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('spec', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('feedback', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tests.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=12)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('attempts_allowed', models.PositiveIntegerField(default=1)),
                ('pass_mark', models.FloatField(default=0)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_options', models.BooleanField(default=True)),
                ('show_feedback_mode', models.CharField(default='after_close', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lesson.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='started', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('pass_mark', models.FloatField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text', models.TextField(blank=True)),
                ('free_json', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('needs_manual', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('selected_options', models.ManyToManyField(blank=True, related_name='selected_in', to='tests.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_attempts', to='tests.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.testattempt')),
            ],
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['question'], name='tests_choic_questio_79bd0f_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['lesson'], name='tests_test_lesson__c46df9_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['status'], name='tests_test_status_2fb298_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test'], name='tests_quest_test_id_0e3122_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type'], name='tests_quest_type_6e70af_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test'], name='tests_testa_user_id_a9b45d_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', 'status'], name='tests_testa_test_id_620d47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('test', 'user', 'attempt_no')},
        ),
        migrations.AddIndex(
            model_name='answerattempt',
            index=models.Index(fields=['attempt', 'question'], name='tests_answe_attempt_495708_idx'),
        ),
        migrations.AddIndex(
            model_name='answerattempt',
            index=models.Index(fields=['question'], name='tests_answe_questio_098eb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answerattempt',
            unique_together={('attempt', 'question')},
        ),
    ]
