# Generated by Django 5.2.4 on 2025-09-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', 'Single choice'), ('multiple', 'Multiple choice'), ('true_false', 'True/False'), ('short', 'Short answer'), ('long', 'Long answer'), ('code', 'Code (manual grade)'), ('match', 'Matching'), ('order', 'Ordering')], max_length=16),
        ),
        migrations.AlterField(
            model_name='test',
            name='attempts_allowed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
