# Generated by Django 5.2.4 on 2025-08-08 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_alter_test_lesson'),
        ('tests', '0005_remove_testresult_score_alter_testresult_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lesson.lesson'),
            preserve_default=False,
        ),
    ]
