# Generated by Django 5.2.4 on 2025-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_test_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='score_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
