# Generated by Django 5.2.4 on 2025-08-17 19:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_remove_coursetheory_lesson_remove_openquestion_test_and_more'),
        ('tests', '0007_testresult_correct_count_testresult_score_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text', models.TextField(blank=True)),
                ('free_json', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('needs_manual', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='started', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('pass_mark', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='selected_choice',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='test',
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='choice',
            name='feedback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='spec',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', 'Single choice'), ('multiple', 'Multiple choice'), ('true_false', 'True/False'), ('short', 'Short answer'), ('long', 'Long answer'), ('code', 'Code'), ('match', 'Matching'), ('order', 'Ordering')], default='MC', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='attempts_allowed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='test',
            name='closes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='opens_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='pass_mark',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='show_feedback_mode',
            field=models.CharField(default='after_close', max_length=16),
        ),
        migrations.AddField(
            model_name='test',
            name='shuffle_options',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='test',
            name='time_limit_sec',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['question'], name='tests_choic_questio_79bd0f_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test'], name='tests_quest_test_id_0e3122_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type'], name='tests_quest_type_6e70af_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['lesson'], name='tests_test_lesson__c46df9_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['status'], name='tests_test_status_2fb298_idx'),
        ),
        migrations.AddField(
            model_name='answerattempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_attempts', to='tests.question'),
        ),
        migrations.AddField(
            model_name='answerattempt',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='selected_in', to='tests.choice'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests.test'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerattempt',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.testattempt'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test'], name='tests_testa_user_id_a9b45d_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', 'status'], name='tests_testa_test_id_620d47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('test', 'user', 'attempt_no')},
        ),
        migrations.AddIndex(
            model_name='answerattempt',
            index=models.Index(fields=['attempt', 'question'], name='tests_answe_attempt_495708_idx'),
        ),
        migrations.AddIndex(
            model_name='answerattempt',
            index=models.Index(fields=['question'], name='tests_answe_questio_098eb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answerattempt',
            unique_together={('attempt', 'question')},
        ),
    ]
