name: Backend → Prod (build in GitHub, deploy on PROD)

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  OWNER: nekroorganization
  IMAGE_NAME: backend
  IMAGE_TAG: prod
  BACKEND_SERVICE: backend

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_WRITE_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            BUILD_SHA=${{ github.sha }}

  deploy-to-prod:
    needs: build-and-push
    runs-on: self-hosted
    environment: main
    steps:
      - name: Prepare SSH key
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "${{ runner.temp }}"
          KEYFILE="${{ runner.temp }}/prod_ssh_key"
          # приватний ключ у багаторядковому OpenSSH форматі
          printf '%s\n' "${{ secrets.PROD_KEY }}" | sed 's/\r$//' > "$KEYFILE"
          chmod 600 "$KEYFILE"
          PORT="${{ secrets.PROD_SSH_PORT }}"
          [ -z "$PORT" ] && PORT=22
          echo "$PORT" > "${{ runner.temp }}/ssh_port"

      - name: Deploy via SSH
        shell: bash
        run: |
          set -euo pipefail
          KEYFILE="${{ runner.temp }}/prod_ssh_key"
          PORT="$(cat "${{ runner.temp }}/ssh_port")"
          ssh -i "$KEYFILE" -p "$PORT" -o IdentitiesOnly=yes -o StrictHostKeyChecking=no \
            "${{ secrets.PROD_USER }}@${{ secrets.PROD_TARGET_HOST }}" \
            GHCR_USER='${{ secrets.GHCR_USER }}' \
            GHCR_READ_TOKEN='${{ secrets.GHCR_READ_TOKEN }}' \
            BACKEND_SERVICE='${{ env.BACKEND_SERVICE }}' \
            bash -s <<'EOF'
set -euo pipefail
cd /opt/myapp

# логін у GHCR для pull (не падаємо, якщо вже залогінені)
if [ -n "${GHCR_USER:-}" ] && [ -n "${GHCR_READ_TOKEN:-}" ]; then
  echo "$GHCR_READ_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin || true
fi

docker compose pull "$BACKEND_SERVICE"
docker compose up -d "$BACKEND_SERVICE"
docker image prune -f
EOF

      - name: Cleanup SSH key
        if: always()
        run: |
          rm -f "${{ runner.temp }}/prod_ssh_key"
