name: Backend → Prod (build in GitHub, run on PROD via Runner)

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  OWNER: nekroorganization       # тільки нижні літери!
  IMAGE_NAME: backend

permissions:
  contents: read
  packages: write                # для пушу в GHCR через GITHUB_TOKEN

jobs:
  build-and-push-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR (with PAT)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_WRITE_TOKEN }}

      - name: Build & Push :prod
        uses: docker/build-push-action@v6
        with:
          context: .                   # змінити на ./backend якщо Dockerfile у підтеці
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:prod

  deploy-on-prod:
    needs: build-and-push-prod
    runs-on: [self-hosted, Linux, X64]   # твій той самий runner
    environment: main                    # бере secrets із env "main"
    steps:
      - name: Deploy via runner → prod
        env:
          GHCR_USER:  ${{ secrets.GHCR_USER }}          # потрібні тільки якщо образи приватні
          GHCR_TOKEN: ${{ secrets.GHCR_READ_TOKEN }}
          TARGET:     ${{ secrets.PROD_TARGET_HOST }}   # напр. dev@172.17.10.23
        run: |
          # якщо образи приватні — runner залогінить prod у GHCR,
          # а далі на prod: compose pull/up для всіх сервісів (backend, frontend, nginx)
          /opt/deploy/deploy-myapp.sh "${TARGET}"
