name: Backend → Tester (remote build)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set target
        run: |
          echo "HOST=${{ secrets.TARGET_HOST }}" >> $GITHUB_ENV
          echo "USER=${{ secrets.TARGET_USER }}" >> $GITHUB_ENV
          echo "PORT=${{ secrets.TARGET_SSH_PORT }}" >> $GITHUB_ENV

      - name: Sync code to Tester
        run: |
          mkdir -p "${{ runner.temp }}"
          cat > "${{ runner.temp }}/k" <<'KEY'
${{ secrets.TARGET_SSH_KEY }}
KEY
          chmod 600 "${{ runner.temp }}/k"

          RSYNC_RSH="ssh -i ${{ runner.temp }}/k -p $PORT -o StrictHostKeyChecking=no"

        
          ssh -i "${{ runner.temp }}/k" -p "$PORT" -o StrictHostKeyChecking=no "$USER@$HOST" "echo ok"

      
          ssh -i "${{ runner.temp }}/k" -p "$PORT" -o StrictHostKeyChecking=no "$USER@$HOST" "mkdir -p /opt/brainboost/src/backend"
          rsync -az --delete --exclude ".git" --exclude "node_modules" --exclude ".github" \
            -e "$RSYNC_RSH" ./ "$USER@$HOST:/opt/brainboost/src/backend/"
